### ISSUE TITLE
Allow changing response language in the UI

### ISSUE THREAD

**Issue by vivekuppal** [vivekuppal/transcribe#52]
Currently the response language of LLM can be set in the parameters.yaml.
Allow user to set the language using UI.
Users choice should be persisted across restarts of the application.

**Comment by chenosyong** [comment]
HI, response_lang: UI still displays English after setting it to chinese OR zh-CN. Could you help me answer this question? Thank you！

**Comment by chenosyong** [comment]
Hello, response_lang: set as chinese OR zh-CN, save and restart, but the UI still displays English. Could you please help me answer this question? Thank you！

**Comment by chenosyong** [comment]
The first save on the UI is not valid, directly set the response_lang: of parameters.yaml to Chinese or zh-CN, save and restart, but the UI still shows English and content。
![433434](https://github.com/vivekuppal/transcribe/assets/45561559/78438cc1-afeb-48d1-a1d2-63450ccf7cbb)

**Comment by vivekuppal** [comment]
Really appreciate the feedback on several fronts.
I think one of the things I am realizing is that product configuration is slightly complex to get it right for non English language. This needs to be simplified for the end user.

I made the following changes that give a much better response in Chinese.

Make following changes in `parameters.yaml`.
The commented items are English versions and the non-commented items are corresponding Chinese versions

```
#  response_lang: English
  response_lang: Chinese

  #  default_prompt_preamble: "You are a casual pal, genuinely interested in the conversation at hand. A poor transcription of conversation is given below. "
  default_prompt_preamble: "你是一个随意的朋友，对当前的谈话真正感兴趣。 下面是一段糟糕的谈话记录。 "
  # default_prompt_epilogue: "Please respond, in detail, to the conversation. Confidently give a straightforward response to the speaker, even if you don't understand them. Give your response in square brackets. DO NOT ask to repeat, and DO NOT ask for clarification. Just answer the speaker directly."
  default_prompt_epilogue: "请详细回复对话。 即使您不明白说话者的意思，也要自信地给出直截了当的答复。 在方括号中给出你的答案。 不要要求重复，也不要要求澄清。 直接回答说话者即可。 "

  system_prompt: "You are a casual pal, genuinely interested in the conversation at hand. Please respond, in detail, to the conversation. Confidently give a straightforward response to the speaker, even if you don't understand them. Give your response in square brackets. DO NOT ask to repeat, and DO NOT ask for clarification. Just answer the speaker directly."
  system_prompt: "你是一个随意的朋友，对当前的谈话真正感兴趣。 请详细回复对话。 即使您不明白说话者的意思，也要自信地给出直截了当的答复。 在方括号中给出你的答案。 不要要求重复，也不要要求澄清。 直接回答说话者即可。 "

  # summary_prompt: 'Create a summary of the following text'
  summary_prompt: '创建以下文本的摘要 '

  initial_convo:
    first:
      role: "You"
      # content: Hey assistant, how are you doing today, I am in mood of a casual conversation.
      content: "你是一个随意的朋友，对当前的谈话真正感兴趣。 下面是一段糟糕的谈话记录。 "
    second:
      role: "assistant"
      # content: "Hello, V. You are awesome. I am doing very well and looking forward to some light hearted banter with you."
      content: "你好，V。你太棒了。 我做得很好，期待着与你进行一些轻松的玩笑。 "

```

![image](https://github.com/vivekuppal/transcribe/assets/11325412/131c814d-8c75-4b23-bd92-cf8cc36da8fd)

I suspect the settings you changed were slightly different than those highlighted above. That might explain some of the differences you are seeing.
